---
title: "Questionário Hospitalar sobre Cultura de Segurança do Paciente - HSOPSC
  versão 2.0"
author: "Thais Pereira"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
## pacotes 

library("tidyverse")
library("readxl")
library('googlesheets4')
library("janitor")
library ("abjData")
library("geobr")
library("dplyr")
library("tidyr")
library("purrr")


```



```{r}

gs4_deauth()
dados <- read_sheet(ss = "https://docs.google.com/spreadsheets/d/1Zydeu1lZf6rzGeZ3byB_I23TFw9FPqZHn3yYI0LIP_E/edit#gid=0", sheet = 1) 

```



```{r}


dados_respondentes <- dados %>%  select(-2:-6) %>% 
  mutate_all(trimws) %>% 
  mutate(cargo = paste(Enfermagem, Medicina, `Outra Profissão de Saúde`,
                       `Supervisor, Gerente, Líder de equipe/clínica, Alta liderança` , `Apoio`)) %>% 
  mutate(area = paste(`Múltiplas Unidades/Nenhuma Unidade específica`,
                     `Unidades Clínicas/Cirúrgicas`,
                     `Unidades de Cuidados Especializados`,
                     `Serviços Cirúrgicos`,
                     `Serviços Clínicos`, 
                     `Administração/Gestão`,
                     `Serviços de Apoio`)) %>% 
  select(-2:-7, 59, 8, -9:-16, 17, -18:-43, -46:-51, -57) %>% 
  mutate(area = gsub("\\bNA\\b", "", area)) %>% 
  mutate(cargo = gsub("\\bNA\\b", "", cargo)) %>% 
  mutate_all(trimws) %>% 
  select(-2, -3)

dados_respondentes %>% 
   write_sheet(ss = "https://docs.google.com/spreadsheets/d/1Zydeu1lZf6rzGeZ3byB_I23TFw9FPqZHn3yYI0LIP_E/edit#gid=0", sheet = 3)
  

dados_respondentes_1 <- dados_respondentes %>% 
  mutate(cargo = case_when(cargo == "Enfermeiro" ~ "1", 
                           cargo == "Técnico de Enfermagem" ~ "2", 
                           cargo == "Auxiliar de Enfermagem" ~ "3",
                           cargo == "Residente de Enfermagem" ~ '4',
                           cargo == "Estagiário de Enfermagem (Graduação)" ~ '5',
                           cargo == "Médico" ~ "6",
                           cargo == "Médico Hospitalista" ~ "7",
                           cargo == "Residente de Medicina" ~ "8",
                           cargo == "Interno de Medicina" ~ "9",
                           cargo == "Nutricionista" ~ "10",
                           cargo == "Farmacêutico, Técnico ou Auxiliar de Farmácia" ~ "11",
                           cargo == "Fisioterapeuta, Terapeuta Ocupacional ou Fonoaudiólogo" ~ "12",
                           cargo == "Psicólogo" ~ "13",
                           cargo == "Psicóloga" ~ "13",
                           cargo == "Bioquímico" ~ "14",
                           cargo == "Assistente Social" ~ "15",
                           cargo == "Dentista" ~ "16",
                           cargo == "Técnico (por exemplo, de Laboratório, Rx, Eletrocardiograma)" ~ "17",
                           cargo == "Supervisor, Gerente de Departamento, Chefe de equipe/clínica, Administrador, Diretor" ~ "18",
                           cargo == "Superintendente, Diretor Geral, Diretor Presidente" ~ "19",
                           cargo == "Hotelaria, Manutenção e Infraestrutura" ~ "20",
                           cargo == "Serviço de Nutrição e Dietética" ~ "21",
                           cargo == "Serviço de Limpeza" ~ "22",
                           cargo == "Tecnologia da Informação, Serviço de Informações em Saúde, Informática Médica" ~ "23",
                           cargo == "Segurança" ~ '24',
                           cargo == "Transporte" ~ "25",
                           cargo == "Funcionário ou Secretário de unidade, Recepcionista, Funcionário Administrativo" ~ "26",
                           cargo == "Outro, por favor especifique:" ~ "27", TRUE ~ (cargo))) %>% 
    mutate(area = case_when(area == "Vários setores hospitalares/ nenhum setor específico" ~ "1", 
                           area == "Unidade Mista Clínica e Cirúrgica" ~ "2", 
                           area == "Unidade Clínica (Não-Cirúrgica)" ~ '3',
                           area == "Unidade Cirúrgica" ~ "4",
                           area == "Central de Material e Esterilização (CME)" ~ "5",
                           area == "Cardiologia" ~ "6",
                           area == "Serviço de Emergência, Observação, Curta Permanência" ~ "7",
                           area == "Gastroenterologia" ~ "8",
                           area == "UTI (adulto - todos os tipos)" ~ "9",
                           area == "Maternidade, Obstetrícia, Ginecologia" ~ "10",
                           area == "Oncologia, Hematologia" ~ "11",
                           area == "Pediatria (incluindo UTI Neonatal e Pediátrica)" ~ "12",
                           area == "Psiquiatria e Saúde Mental" ~ "13",
                           area == "Pneumologia" ~ "14",
                           area == "Reabilitação, Fisiatria" ~ "15",
                           area == "Anestesiologia" ~ "16",
                           area == "Endoscopia, Colonoscopia" ~ "17",
                           area == "Pré Operatório, Centro Cirúrgico/Recuperação Pós Anestésica/Pós Operatório" ~ "18",
                           area == "Patologia/Laboratório" ~ "19",
                           area == "Farmácia" ~ "20",
                           area == "Radiologia, Exames de Imagem" ~ "21",
                           area == "Terapia Respiratória" ~ "22",
                           area == "Serviço Social, Planejamento de Alta" ~ '23',
                           area == "Administração, Gestão" ~ '24',
                           area == "Serviços Financeiros, Faturamento" ~ '25',
                           area == "Recursos Humanos, Treinamento" ~ "26",
                           area == "Educação Continuada" ~ "27", 
                           area == "Tecnologia da Informação, Gestão da Informação em Saúde, Informática Clínica" ~ "28",
                           area == "Setor de Arquivo Médico (SAME)"  ~ "29",
                           area == "Qualidade, Gestão de Risco, Segurança do Paciente" ~ "30",
                           area == "Recepção, Cadastro" ~ "31",
                           area == "Serviço de Nutrição e Dietética" ~ "32",
                           area == "Serviço de Limpeza, Hotelaria, Manutenção e Infraestrutura" ~ "33",
                           area == "Serviço de Segurança" ~ "34",
                           area == "Transporte" ~ '35', TRUE ~ (area))) %>% 
  rename(id = ID)
  


  

```


```{r}

dados_1 <- dados %>% janitor::clean_names() %>% select(-2:-22) %>% mutate_all(trimws)

colunas <- c("nesta_unidade_trabalhamos_juntos_como_uma_equipe_integrada", "nesta_unidade_temos_profissionais_suficientes_para_lidar_com_a_carga_de_trabalho", "os_profissionais_desta_unidade_trabalham_mais_horas_do_que_seria_o_desejavel_para_prestar_o_melhor_cuidado_ao_paciente", "esta_unidade_revisa_regularmente_os_processos_de_trabalho_para_determinar_se_sao_necessarias_mudancas_para_melhorar_a", "esta_unidade_depende_demasiado_de_profissionais_com_contrato_terceirizado_ou_contratado_por_qualquer_outro_regime_temporario",  "nesta_unidade_os_profissionais_sentem_que_seus_erros_falhas_podem_ser_usados_contra_eles", 
"quando_um_incidente_e_notificado_nesta_unidade_a_impressao_que_se_tem_e_que_a_pessoa_esta_sendo_notificada_e_nao_o_problema", "durante_periodos_de_sobrecarga_de_trabalho_os_profissionais_desta_unidade_ajudam_uns_aos_outros", "ha_problema_com_comportamento_desrespeitoso_por_parte_daqueles_que_trabalham_nesta_unidade", "quando_os_profissionais_cometem_erros_esta_unidade_se_concentra_no_aprendizado_ao_inves_de_culpar_os_individuos", "o_ritmo_de_trabalho_nesta_unidade_e_tao_intenso_que_afeta_negativamente_a_seguranca_do_paciente", "nesta_unidade_as_mudancas_para_melhorar_a_seguranca_do_paciente_sao_avaliadas_para_verificar_se_elas_estao_funcionando_bem",  "nesta_unidade_falta_apoio_aos_profissionais_envolvidos_em_erros_falhas_que_comprometem_a_seguranca_do_paciente", "esta_unidade_permite_que_os_mesmos_continuem_ocorrendo_problemas_de_seguranca_do_paciente", 
"meu_supervisor_gerente_ou_chefe_de_equipe_clinica_considera_seriamente_as_sugestoes_dos_profissionais_para_melhorar_a_seguranca_do_paciente", "meu_supervisor_gerente_ou_chefe_de_equipe_clinica_quer_que_trabalhemos_mais_rapido_nos_horarios_de_demanda_intensa_de_trabalho_mesmo_que_isso_implique_em_pular_etapas", "meu_supervisor_gerente_ou_chefe_de_equipe_clinica_adota_medidas_para_resolver_as_questoes_de_seguranca_do_paciente_que_lhe_sao_apresentadas", "as_acoes_da_gestao_do_hospital_demonstram_que_a_seguranca_do_paciente_tem_alta_prioridade", 
"a_gestao_do_hospital_fornece_recursos_adequados_para_melhorar_a_seguranca_do_paciente", 
"a_gestao_do_hospital_parece_ter_interesse_na_seguranca_do_paciente_somente_apos_a_ocorrencia_de_um_evento_adverso", 
"quando_pacientes_sao_transferidos_de_uma_unidade_para_outra_informacoes_importantes_sobre_o_seu_cuidado_sao_frequentemente_perdidas", 
"durante_as_mudancas_de_turno_plantao_informacoes_importantes_sobre_o_cuidado_do_paciente_frequentemente_sao_omitidas", 
"durante_as_mudancas_de_turno_plantao_ha_tempo_suficiente_para_trocar_todas_as_informacoes_importantes_para_o_cuidado_do_paciente")

colunas_2 <- c("somos_informados_sobre_os_erros_incidentes_de_seguranca_que_acontecem_nesta_unidade", 
               "quando_acontecem_erros_incidentes_de_seguranca_nessa_unidade_discutimos_maneiras_de_evitar_que_voltem_a_acontecer", "nesta_unidade_somos_informados_sobre_as_mudancas_realizadas_com_base_nos_relatorios_de_notificacao_de_incidentes", 
"nesta_unidade_os_profissionais_se_falam_abertamente_quando_veem_algo_que_pode_afetar_negativamente_o_cuidado_do_paciente", 
"quando_os_profissionais_desta_unidade_veem_alguem_com_mais_autoridade_fazendo_algo_inseguro_para_os_pacientes_eles_falam_abertamente",
"quando_os_profissionais_desta_unidade_se_manifestam_as_pessoas_com_mais_autoridade_estao_abertas_as_suas_preocupacoes_em_relacao_a_seguranca_do_paciente", 
"nesta_unidade_os_profissionais_tem_receio_de_fazer_perguntas_quando_algo_nao_lhes_parece_certo", 
"quando_um_incidente_e_detectado_e_corrigido_antes_de_atingir_o_paciente_com_que_frequencia_ele_e_notificado",
"quando_um_incidente_atinge_o_paciente_e_poderia_ter_lhe_causado_dano_mas_nao_lhe_causou_com_que_frequencia_ele_e_notificado")


dados_2 <- dados_1  %>% 
mutate(avaliacao = case_when(avaliacao == "Ruim" ~ 1, 
                             avaliacao == "Razoável" ~ 2,
                             avaliacao == "Boa" ~ 3,
                             avaliacao == "Muita boa" ~ 4,
                             avaliacao == "Excelente" ~ 5)) %>% 
  mutate(across(all_of(colunas), ~case_when(
         . == "Discordo totalmente" ~ 1,
         . == "Discordo Totalmente" ~ 1,
         . ==  "Discordo" ~ 2, 
         . ==  "Não concordo nem discordo" ~ 3,
         . ==  "Concordo" ~ 4,
         . ==  "Concordo Totalmente" ~ 5,
         . ==  "Concordo totalmente" ~ 5,
         . ==  "Não se aplica ou não sei" ~ 9,
           ))) %>% 
  mutate(across(all_of(colunas_2), ~case_when(
         . == "Nunca" ~ 1, 
         . ==  "Raramente" ~ 2, 
         . ==  "Às vezes" ~ 3,
         . ==  "Às vezes" ~ 3,
         . ==  "Quase sempre" ~ 4,
         . ==  "Sempre" ~ 5,
         . ==  "Não se aplica ou não sei" ~ 9,
         . ==  "Não sei ou não se aplica" ~ 9))) %>% 
  mutate(nos_ultimos_doze_meses_quantos_incidentes_relacionados_a_seguranca_do_paciente_voce_notificou = case_when(nos_ultimos_doze_meses_quantos_incidentes_relacionados_a_seguranca_do_paciente_voce_notificou == "Nenhum" ~ "A",
                                                                                                                   nos_ultimos_doze_meses_quantos_incidentes_relacionados_a_seguranca_do_paciente_voce_notificou == "1 a 2" ~ "B", 
                                                                                                  nos_ultimos_doze_meses_quantos_incidentes_relacionados_a_seguranca_do_paciente_voce_notificou == "3 a 5" ~ "C", 
                                                                                                                   nos_ultimos_doze_meses_quantos_incidentes_relacionados_a_seguranca_do_paciente_voce_notificou == "6 a 10" ~ "D",
                                                                                                                   nos_ultimos_doze_meses_quantos_incidentes_relacionados_a_seguranca_do_paciente_voce_notificou == "11 ou mais" ~ "E", 
                                                                                                  TRUE ~ (nos_ultimos_doze_meses_quantos_incidentes_relacionados_a_seguranca_do_paciente_voce_notificou))) %>% 
  mutate(ha_quanto_tempo_voce_trabalha_neste_hospital = case_when(ha_quanto_tempo_voce_trabalha_neste_hospital == "Menos que 1 ano" ~ "A",
                                                                  ha_quanto_tempo_voce_trabalha_neste_hospital == "1 a 5 anos" ~ "B",
                                                                  ha_quanto_tempo_voce_trabalha_neste_hospital == "6 a 10 anos" ~ "C",
                                                                  ha_quanto_tempo_voce_trabalha_neste_hospital == "11 anos ou mais" ~ "D", TRUE ~ (ha_quanto_tempo_voce_trabalha_neste_hospital))) %>% 
  mutate(neste_hospital_ha_quanto_tempo_voce_trabalha_na_sua_atual_unidade_area_de_trabalho= case_when(neste_hospital_ha_quanto_tempo_voce_trabalha_na_sua_atual_unidade_area_de_trabalho == "Menos que 1 ano" ~ "A", 
                                                                                                       neste_hospital_ha_quanto_tempo_voce_trabalha_na_sua_atual_unidade_area_de_trabalho == "1 a 5 anos" ~ "B",
                                                                                                       neste_hospital_ha_quanto_tempo_voce_trabalha_na_sua_atual_unidade_area_de_trabalho == "6 a 10 anos" ~ "C",
                                                                                                       neste_hospital_ha_quanto_tempo_voce_trabalha_na_sua_atual_unidade_area_de_trabalho == "11 anos ou mais" ~ "D", TRUE ~ (neste_hospital_ha_quanto_tempo_voce_trabalha_na_sua_atual_unidade_area_de_trabalho))) %>% 
  
mutate(normalmente_quantas_horas_por_semana_voce_trabalha_neste_hospital = 
         case_when(normalmente_quantas_horas_por_semana_voce_trabalha_neste_hospital == "Menos que 30 horas por semana" ~ "A", 
                   normalmente_quantas_horas_por_semana_voce_trabalha_neste_hospital == "30 a 40 horas por semana" ~ "B",
                   normalmente_quantas_horas_por_semana_voce_trabalha_neste_hospital == "Mais que 40 horas por semana" ~ "C", TRUE ~ (normalmente_quantas_horas_por_semana_voce_trabalha_neste_hospital))) %>% 
  mutate(no_seu_cargo_funcao_em_geral_voce_tem_interacao_ou_contato_direto_com_os_pacientes= case_when(no_seu_cargo_funcao_em_geral_voce_tem_interacao_ou_contato_direto_com_os_pacientes == "SIM, em geral, tenho interação ou contato direto com os pacientes" ~ "A", 
                                                                                                      no_seu_cargo_funcao_em_geral_voce_tem_interacao_ou_contato_direto_com_os_pacientes == "NÃO, em geral, NÃO tenho interação ou contato direto com os pacientes" ~ "B", TRUE ~  (no_seu_cargo_funcao_em_geral_voce_tem_interacao_ou_contato_direto_com_os_pacientes))) %>% 
  select(-obrigado_por_preencher_este_questionario)



```



```{r}

dados_respondentes_1 %>% 
  left_join(dados_2, by = c("id")) %>% 
   write_sheet(ss = "https://docs.google.com/spreadsheets/d/1Zydeu1lZf6rzGeZ3byB_I23TFw9FPqZHn3yYI0LIP_E/edit#gid=0", sheet = 2)

```
























